
export let consistencySlider: HTMLInputElement;
export let storyConsistencyContainer: HTMLDivElement;
export let timeDeltaDisplay: HTMLSpanElement;
export let storyChainWrapper: HTMLDivElement;
export let viewDashboard: HTMLDivElement;
export let viewStudio: HTMLDivElement;
export let projectGrid: HTMLDivElement;
export let dashboardSettings: HTMLDivElement;

export let imageGallery: HTMLDivElement;
export let historyList: HTMLDivElement;
export let projectSelector: HTMLSelectElement;
export let showroomAssetPreview: HTMLImageElement;
export let audioContainer: HTMLDivElement;
export let audioFilename: HTMLSpanElement;
export let audioPlayer: HTMLAudioElement;
export let directorsCutToggle: HTMLInputElement;
export let improverModal: HTMLDivElement;
export let homeBtn: HTMLButtonElement;
export let modeGenerateBtn: HTMLButtonElement;
export let modeEditBtn: HTMLButtonElement;
export let modeReferenceBtn: HTMLButtonElement;
export let modeRemixBtn: HTMLButtonElement;
export let modeCanvasBtn: HTMLButtonElement;
export let modeShowroomBtn: HTMLButtonElement;
export let modeAgentBtn: HTMLButtonElement;
export let agentWindow: HTMLDivElement;
export let agentInput: HTMLInputElement;
export let infiniteReelRadio: HTMLInputElement;
export let keyframeModeRadio: HTMLInputElement;
export let musicModeRadio: HTMLInputElement;
export let motionBrushRadio: HTMLInputElement;
export let agentModeRadio: HTMLInputElement;
export let generateTrigger: HTMLButtonElement;
export let genActionImage: HTMLButtonElement;
export let genActionVideo: HTMLButtonElement;
export let storyChainCheckbox: HTMLInputElement;
export let editBibleBtn: HTMLButtonElement;
export let bibleProjectName: HTMLInputElement;
export let bibleContext: HTMLTextAreaElement;
export let bibleModal: HTMLDivElement;
export let closeBibleBtn: HTMLButtonElement;
export let magicBtn: HTMLButtonElement;
export let improveBtn: HTMLButtonElement;
export let savePromptBtn: HTMLButtonElement;
export let loadPromptBtn: HTMLButtonElement;
export let closeLibraryBtn: HTMLButtonElement;
export let promptLibraryModal: HTMLDivElement;
export let clearPromptBtn: HTMLButtonElement;
export let promptEl: HTMLTextAreaElement;
export let acceptImprovementBtn: HTMLButtonElement;
export let cancelImprovementBtn: HTMLButtonElement;
export let closeModalBtn: HTMLButtonElement;
export let fileInput: HTMLInputElement;
export let dropZone: HTMLDivElement;
export let remixContentDrop: HTMLDivElement;
export let remixStyleDrop: HTMLDivElement;
export let showroomMockupBtn: HTMLButtonElement;
export let showroomVideoBtn: HTMLButtonElement;
export let magicMotionBtn: HTMLButtonElement;
export let canvasToolPan: HTMLButtonElement;
export let canvasToolGenerate: HTMLButtonElement;
export let canvasUploadBtn: HTMLButtonElement;
export let canvasResetView: HTMLButtonElement;
export let canvasClear: HTMLButtonElement;
export let canvasInfoBtn: HTMLButtonElement;
export let closeCanvasHelpBtn: HTMLButtonElement;
export let exitCanvasBtn: HTMLButtonElement;
export let closeVideoConfigBtn: HTMLButtonElement;
export let videoConfigModal: HTMLDivElement;
export let videoGridInstruction: HTMLDivElement;
export let draftModeRadio: HTMLInputElement;
export let cancelAnnotationBtn: HTMLButtonElement;
export let saveAnnotationBtn: HTMLButtonElement;
export let clearMaskBtn: HTMLButtonElement;
export let invertMaskBtn: HTMLButtonElement;
export let toolBrushBtn: HTMLButtonElement;
export let toolEraserBtn: HTMLButtonElement;
export let brushSizeInput: HTMLInputElement;
export let annotationCanvas: HTMLCanvasElement;
export let lightboxClose: HTMLButtonElement;
export let lightboxModal: HTMLDivElement;
export let lightboxPrev: HTMLButtonElement;
export let lightboxNext: HTMLButtonElement;
export let lightboxPlayReelBtn: HTMLButtonElement;
export let lightboxDownload: HTMLButtonElement;
export let exportReelBtn: HTMLButtonElement;
export let lightboxCompareBtn: HTMLButtonElement;
export let openHistoryBtn: HTMLButtonElement;
export let historySidebar: HTMLDivElement;
export let closeHistoryBtn: HTMLButtonElement;
export let downloadAllBtn: HTMLButtonElement;
export let clearHistoryBtn: HTMLButtonElement;
export let closeStoryboardBtn: HTMLButtonElement;
export let storyboardContainer: HTMLDivElement;
export let removeAudioBtn: HTMLButtonElement;
export let agentApprovalModal: HTMLDivElement;
export let agentUploadBtn: HTMLButtonElement;
export let agentFileInput: HTMLInputElement;
export let filmScrollLeft: HTMLButtonElement;
export let filmScrollRight: HTMLButtonElement;
export let filmStripContainer: HTMLDivElement;
export let infiniteCanvasContainer: HTMLDivElement;
export let infiniteCanvas: HTMLCanvasElement;
export let canvasHud: HTMLDivElement;
export let canvasEmptyState: HTMLDivElement;
export let canvasHelpCard: HTMLDivElement;
export let showroomContainer: HTMLDivElement;
export let showroomDropZone: HTMLDivElement;
export let showroomProductType: HTMLSelectElement;
export let showroomPlacement: HTMLSelectElement;
export let showroomMotionPrompt: HTMLTextAreaElement;
export let statusEl: HTMLDivElement;
export let currentMockup: HTMLImageElement;
export let showroomAsset: HTMLImageElement;
export let countContainer: HTMLDivElement;
export let uploadPlaceholder: HTMLDivElement;
export let galleryHint: HTMLDivElement;
export let galleryActionBtn: HTMLButtonElement;
export let selectionCountEl: HTMLSpanElement;
export let anchorStatusEl: HTMLDivElement;
export let remixContentPreview: HTMLImageElement;
export let remixStylePreview: HTMLImageElement;
export let generationCountEl: HTMLInputElement;
export let aspectRatioEl: HTMLSelectElement;
export let resolutionEl: HTMLSelectElement;
export let seedInput: HTMLInputElement;
export let negativePromptInput: HTMLInputElement;
export let processorVideo: HTMLVideoElement;
export let processorCanvas: HTMLCanvasElement;
export let annotationImage: HTMLImageElement;
export let annotationTitle: HTMLHeadingElement;
export let annotationModal: HTMLDivElement;
export let lightboxImage: HTMLImageElement;
export let lightboxVideo: HTMLVideoElement;
export let lightboxEditBtn: HTMLButtonElement;
export let filmStripList: HTMLDivElement;
export let promptList: HTMLDivElement;
export let improverContent: HTMLDivElement;
export let improverLoading: HTMLDivElement;
export let originalPromptDisplay: HTMLDivElement;
export let storyboardGrid: HTMLDivElement;
export let agentSendBtn: HTMLButtonElement;
export let agentMinimizeBtn: HTMLButtonElement;
export let agentCloseBtn: HTMLButtonElement;
export let agentClearBtn: HTMLButtonElement;
export let agentChatContainer: HTMLDivElement;
export let approvalImageContainer: HTMLDivElement;
export let approvalContent: HTMLTextAreaElement;
export let approvalApproveBtn: HTMLButtonElement;
export let approvalRejectBtn: HTMLButtonElement;
export let approvalImage: HTMLImageElement;

export let toastContainer: HTMLDivElement;

// New Selectors for Collapsible Panels & Menus
export let promptBuilderToggle: HTMLButtonElement;
export let promptBuilderContent: HTMLDivElement;
export let promptBuilderArrow: SVGElement;
export let studioControlToggle: HTMLButtonElement;
export let studioControlContent: HTMLDivElement;
export let studioControlArrow: SVGElement;
export let modeGenerateMenu: HTMLDivElement;
export let modeGenImage: HTMLButtonElement;
export let modeGenVideo: HTMLButtonElement;

export function initDOM() {
    consistencySlider = document.querySelector('#consistency-slider') as HTMLInputElement;
    storyConsistencyContainer = document.querySelector('#story-consistency-container') as HTMLDivElement;
    timeDeltaDisplay = document.querySelector('#time-delta-display') as HTMLSpanElement;
    storyChainWrapper = document.querySelector('#story-chain-wrapper') as HTMLDivElement;
    viewDashboard = document.querySelector('#view-dashboard') as HTMLDivElement;
    viewStudio = document.querySelector('#view-studio') as HTMLDivElement;
    projectGrid = document.querySelector('#project-grid') as HTMLDivElement;
    dashboardSettings = document.querySelector('#dashboard-settings') as HTMLDivElement;
    imageGallery = document.querySelector('#image-gallery') as HTMLDivElement;
    historyList = document.querySelector('#history-list') as HTMLDivElement;
    projectSelector = document.querySelector('#project-selector') as HTMLSelectElement;
    showroomAssetPreview = document.querySelector('#showroom-asset-preview') as HTMLImageElement;
    audioContainer = document.querySelector('#audio-container') as HTMLDivElement;
    audioFilename = document.querySelector('#audio-filename') as HTMLSpanElement;
    audioPlayer = document.querySelector('#audio-player') as HTMLAudioElement;
    directorsCutToggle = document.querySelector('#directors-cut-toggle') as HTMLInputElement;
    improverModal = document.querySelector('#improver-modal') as HTMLDivElement;
    homeBtn = document.querySelector('#home-btn') as HTMLButtonElement;
    modeGenerateBtn = document.querySelector('#mode-generate-btn') as HTMLButtonElement;
    modeEditBtn = document.querySelector('#mode-edit-btn') as HTMLButtonElement;
    modeReferenceBtn = document.querySelector('#mode-reference-btn') as HTMLButtonElement;
    modeRemixBtn = document.querySelector('#mode-remix-btn') as HTMLButtonElement;
    modeCanvasBtn = document.querySelector('#mode-canvas-btn') as HTMLButtonElement;
    modeShowroomBtn = document.querySelector('#mode-showroom-btn') as HTMLButtonElement;
    modeAgentBtn = document.querySelector('#mode-agent-btn') as HTMLButtonElement;
    agentWindow = document.querySelector('#agent-window') as HTMLDivElement;
    agentInput = document.querySelector('#agent-input') as HTMLInputElement;
    infiniteReelRadio = document.querySelector('#infinite-reel-radio') as HTMLInputElement;
    keyframeModeRadio = document.querySelector('#keyframe-mode-radio') as HTMLInputElement;
    musicModeRadio = document.querySelector('#music-mode-radio') as HTMLInputElement;
    motionBrushRadio = document.querySelector('#motion-brush-radio') as HTMLInputElement;
    agentModeRadio = document.querySelector('#agent-mode-radio') as HTMLInputElement;
    generateTrigger = document.querySelector('#generate-trigger') as HTMLButtonElement;
    genActionImage = document.querySelector('#gen-action-image') as HTMLButtonElement;
    genActionVideo = document.querySelector('#gen-action-video') as HTMLButtonElement;
    storyChainCheckbox = document.querySelector('#story-chain-checkbox') as HTMLInputElement;
    editBibleBtn = document.querySelector('#edit-bible-btn') as HTMLButtonElement;
    bibleProjectName = document.querySelector('#bible-project-name') as HTMLInputElement;
    bibleContext = document.querySelector('#bible-context') as HTMLTextAreaElement;
    bibleModal = document.querySelector('#bible-modal') as HTMLDivElement;
    closeBibleBtn = document.querySelector('#close-bible-btn') as HTMLButtonElement;
    magicBtn = document.querySelector('#magic-btn') as HTMLButtonElement;
    improveBtn = document.querySelector('#improve-btn') as HTMLButtonElement;
    savePromptBtn = document.querySelector('#save-prompt-btn') as HTMLButtonElement;
    loadPromptBtn = document.querySelector('#load-prompt-btn') as HTMLButtonElement;
    closeLibraryBtn = document.querySelector('#close-library-btn') as HTMLButtonElement;
    promptLibraryModal = document.querySelector('#prompt-library-modal') as HTMLDivElement;
    clearPromptBtn = document.querySelector('#clear-prompt-btn') as HTMLButtonElement;
    promptEl = document.querySelector('#prompt-el') as HTMLTextAreaElement;
    acceptImprovementBtn = document.querySelector('#accept-improvement-btn') as HTMLButtonElement;
    cancelImprovementBtn = document.querySelector('#cancel-improvement-btn') as HTMLButtonElement;
    closeModalBtn = document.querySelector('#close-modal-btn') as HTMLButtonElement;
    fileInput = document.querySelector('#file-input') as HTMLInputElement;
    dropZone = document.querySelector('#drop-zone') as HTMLDivElement;
    remixContentDrop = document.querySelector('#remix-content-drop') as HTMLDivElement;
    remixStyleDrop = document.querySelector('#remix-style-drop') as HTMLDivElement;
    showroomMockupBtn = document.querySelector('#showroom-mockup-btn') as HTMLButtonElement;
    showroomVideoBtn = document.querySelector('#showroom-video-btn') as HTMLButtonElement;
    magicMotionBtn = document.querySelector('#magic-motion-btn') as HTMLButtonElement;
    canvasToolPan = document.querySelector('#canvas-tool-pan') as HTMLButtonElement;
    canvasToolGenerate = document.querySelector('#canvas-tool-generate') as HTMLButtonElement;
    canvasUploadBtn = document.querySelector('#canvas-upload-btn') as HTMLButtonElement;
    canvasResetView = document.querySelector('#canvas-reset-view') as HTMLButtonElement;
    canvasClear = document.querySelector('#canvas-clear') as HTMLButtonElement;
    canvasInfoBtn = document.querySelector('#canvas-info-btn') as HTMLButtonElement;
    closeCanvasHelpBtn = document.querySelector('#close-canvas-help-btn') as HTMLButtonElement;
    exitCanvasBtn = document.querySelector('#exit-canvas-btn') as HTMLButtonElement;
    closeVideoConfigBtn = document.querySelector('#close-video-config-btn') as HTMLButtonElement;
    videoConfigModal = document.querySelector('#video-config-modal') as HTMLDivElement;
    videoGridInstruction = document.querySelector('#video-grid-instruction') as HTMLDivElement;
    draftModeRadio = document.querySelector('#draft-mode-radio') as HTMLInputElement;
    cancelAnnotationBtn = document.querySelector('#cancel-annotation-btn') as HTMLButtonElement;
    saveAnnotationBtn = document.querySelector('#save-annotation-btn') as HTMLButtonElement;
    clearMaskBtn = document.querySelector('#clear-mask-btn') as HTMLButtonElement;
    invertMaskBtn = document.querySelector('#invert-mask-btn') as HTMLButtonElement;
    toolBrushBtn = document.querySelector('#tool-brush-btn') as HTMLButtonElement;
    toolEraserBtn = document.querySelector('#tool-eraser-btn') as HTMLButtonElement;
    brushSizeInput = document.querySelector('#brush-size-input') as HTMLInputElement;
    annotationCanvas = document.querySelector('#annotation-canvas') as HTMLCanvasElement;
    lightboxClose = document.querySelector('#lightbox-close') as HTMLButtonElement;
    lightboxModal = document.querySelector('#lightbox-modal') as HTMLDivElement;
    lightboxPrev = document.querySelector('#lightbox-prev') as HTMLButtonElement;
    lightboxNext = document.querySelector('#lightbox-next') as HTMLButtonElement;
    lightboxPlayReelBtn = document.querySelector('#lightbox-play-reel-btn') as HTMLButtonElement;
    lightboxDownload = document.querySelector('#lightbox-download') as HTMLButtonElement;
    exportReelBtn = document.querySelector('#export-reel-btn') as HTMLButtonElement;
    lightboxCompareBtn = document.querySelector('#lightbox-compare-btn') as HTMLButtonElement;
    openHistoryBtn = document.querySelector('#open-history-btn') as HTMLButtonElement;
    historySidebar = document.querySelector('#history-sidebar') as HTMLDivElement;
    closeHistoryBtn = document.querySelector('#close-history-btn') as HTMLButtonElement;
    downloadAllBtn = document.querySelector('#download-all-btn') as HTMLButtonElement;
    clearHistoryBtn = document.querySelector('#clear-history-btn') as HTMLButtonElement;
    closeStoryboardBtn = document.querySelector('#close-storyboard-btn') as HTMLButtonElement;
    storyboardContainer = document.querySelector('#storyboard-container') as HTMLDivElement;
    removeAudioBtn = document.querySelector('#remove-audio-btn') as HTMLButtonElement;
    agentApprovalModal = document.querySelector('#agent-approval-modal') as HTMLDivElement;
    agentUploadBtn = document.querySelector('#agent-upload-btn') as HTMLButtonElement;
    agentFileInput = document.querySelector('#agent-file-input') as HTMLInputElement;
    filmScrollLeft = document.querySelector('#film-scroll-left') as HTMLButtonElement;
    filmScrollRight = document.querySelector('#film-scroll-right') as HTMLButtonElement;
    filmStripContainer = document.querySelector('#film-strip-container') as HTMLDivElement;
    infiniteCanvasContainer = document.querySelector('#infinite-canvas-container') as HTMLDivElement;
    infiniteCanvas = document.querySelector('#infinite-canvas') as HTMLCanvasElement;
    canvasHud = document.querySelector('#canvas-hud') as HTMLDivElement;
    canvasEmptyState = document.querySelector('#canvas-empty-state') as HTMLDivElement;
    canvasHelpCard = document.querySelector('#canvas-help-card') as HTMLDivElement;
    showroomContainer = document.querySelector('#showroom-container') as HTMLDivElement;
    showroomDropZone = document.querySelector('#showroom-drop-zone') as HTMLDivElement;
    showroomProductType = document.querySelector('#showroom-product-type') as HTMLSelectElement;
    showroomPlacement = document.querySelector('#showroom-placement') as HTMLSelectElement;
    showroomMotionPrompt = document.querySelector('#showroom-motion-prompt') as HTMLTextAreaElement;
    statusEl = document.querySelector('#status-el') as HTMLDivElement;
    currentMockup = document.querySelector('#current-mockup') as HTMLImageElement;
    showroomAsset = document.querySelector('#showroom-asset') as HTMLImageElement;
    countContainer = document.querySelector('#count-container') as HTMLDivElement;
    uploadPlaceholder = document.querySelector('#upload-placeholder') as HTMLDivElement;
    galleryHint = document.querySelector('#gallery-hint') as HTMLDivElement;
    galleryActionBtn = document.querySelector('#gallery-action-btn') as HTMLButtonElement;
    selectionCountEl = document.querySelector('#selection-count-el') as HTMLSpanElement;
    anchorStatusEl = document.querySelector('#anchor-status-el') as HTMLDivElement;
    remixContentPreview = document.querySelector('#remix-content-preview') as HTMLImageElement;
    remixStylePreview = document.querySelector('#remix-style-preview') as HTMLImageElement;
    generationCountEl = document.querySelector('#generation-count-el') as HTMLInputElement;
    aspectRatioEl = document.querySelector('#aspect-ratio-el') as HTMLSelectElement;
    resolutionEl = document.querySelector('#resolution-el') as HTMLSelectElement;
    seedInput = document.querySelector('#seed-input') as HTMLInputElement;
    negativePromptInput = document.querySelector('#negative-prompt-input') as HTMLInputElement;
    processorVideo = document.querySelector('#processor-video') as HTMLVideoElement;
    processorCanvas = document.querySelector('#processor-canvas') as HTMLCanvasElement;
    annotationImage = document.querySelector('#annotation-image') as HTMLImageElement;
    annotationTitle = document.querySelector('#annotation-title') as HTMLHeadingElement;
    annotationModal = document.querySelector('#annotation-modal') as HTMLDivElement;
    lightboxImage = document.querySelector('#lightbox-image') as HTMLImageElement;
    lightboxVideo = document.querySelector('#lightbox-video') as HTMLVideoElement;
    lightboxEditBtn = document.querySelector('#lightbox-edit-btn') as HTMLButtonElement;
    filmStripList = document.querySelector('#film-strip-list') as HTMLDivElement;
    promptList = document.querySelector('#prompt-list') as HTMLDivElement;
    improverContent = document.querySelector('#improver-content') as HTMLDivElement;
    improverLoading = document.querySelector('#improver-loading') as HTMLDivElement;
    originalPromptDisplay = document.querySelector('#original-prompt-display') as HTMLDivElement;
    storyboardGrid = document.querySelector('#storyboard-grid') as HTMLDivElement;
    agentSendBtn = document.querySelector('#agent-send-btn') as HTMLButtonElement;
    agentMinimizeBtn = document.querySelector('#agent-minimize-btn') as HTMLButtonElement;
    agentCloseBtn = document.querySelector('#agent-close-btn') as HTMLButtonElement;
    agentClearBtn = document.querySelector('#agent-clear-btn') as HTMLButtonElement;
    agentChatContainer = document.querySelector('#agent-chat-container') as HTMLDivElement;
    approvalImageContainer = document.querySelector('#approval-image-container') as HTMLDivElement;
    approvalContent = document.querySelector('#approval-content') as HTMLTextAreaElement;
    approvalApproveBtn = document.querySelector('#approval-approve-btn') as HTMLButtonElement;
    approvalRejectBtn = document.querySelector('#approval-reject-btn') as HTMLButtonElement;
    approvalImage = document.querySelector('#approval-image') as HTMLImageElement;

    toastContainer = document.querySelector('#toast-container') as HTMLDivElement;

    // New Component Selectors
    promptBuilderToggle = document.querySelector('#prompt-builder-toggle') as HTMLButtonElement;
    promptBuilderContent = document.querySelector('#prompt-builder-content') as HTMLDivElement;
    promptBuilderArrow = document.querySelector('#prompt-builder-arrow') as SVGElement;
    
    studioControlToggle = document.querySelector('#studio-control-toggle') as HTMLButtonElement;
    studioControlContent = document.querySelector('#studio-control-content') as HTMLDivElement;
    studioControlArrow = document.querySelector('#studio-control-arrow') as SVGElement;
    
    modeGenerateMenu = document.querySelector('#mode-generate-menu') as HTMLDivElement;
    modeGenImage = document.querySelector('#mode-gen-image') as HTMLButtonElement;
    modeGenVideo = document.querySelector('#mode-gen-video') as HTMLButtonElement;
}
